### PR TITLE
Enhance Language Fetching, Add CDN Support, and Introduce Tolgee.translate Method

### PR DESCRIPTION
**Pull request by TobiasDuelli**
This PR introduces several key updates and improvements to the Tolgee integration:

- **Added CDN Support:** Enables loading resources via a Content Delivery Network for improved performance.

- **Optimized Language Fetching:** Now only the currently selected language is fetched, reducing data usage and load times. Added pagination support for v2 endpoints.

- **Normalize Language Code:** Introduced normalizeLanguageCode to standardize language code usage.

- **New Tolgee.translate Method:** Provides a flexible way to translate text without needing to use Tolgee text widgets. Includes support for fallback values, similar to JavaScript libraries.

**Note:** Passing arguments to the Tolgee.translate method is not yet implemented but will be added in a future update.

### CODE REVIEW

**Comment by JanCizmar** [comment]
Hey! Thanks a lot for this PR. It looks like you had to spend a lot of time on it! <3 

I am assigning it to @Anty0, he is now the Mobile SDK expert in Tolgee. 🚀

**Comment by JanCizmar** [comment]
@TobiasDuelli Are you in our slack community channel? https://tolg.ee/slack ? I would like to DM you, so we can send you some merch for this beautiful PR! 🎉

**Comment by JanCizmar** [comment]
@TobiasDuelli Can you please DM me there? I am not sure I see you.

**Comment by Anty0** [comment]
Hi! Thank you for the MR. Sorry, it took a while to get to you.
I've looked through the MR and made some changes on top of it to fix some issues and improve compatibility for existing codebases, namely:
- There was a bug where an invalid API key would result in an endless loop trying to fetch the first page of translations (since no response would ever result in 200 HTTP code)
- Propagated `currentLanguage` also to the static translations initializer
- Allow omitting `currentLanguage` from the initializer to fall back to the device's default language (this still isn't ideal since there could be a better language available if the device default isn't available).
- Updated the translate method in static translations to allow setting the default value for non-translated strings, following the remote translations example.

New MR, including my changes, is here: #5

**Comment by Anty0** [comment]
@TobiasDuelli Let me know if there is anything I should change in relation to the changes I've made. I'll be releasing a new version soon 🎉

**Pull request closed without merging**
